name: 'sales_dwh'
version: '1.6.0'

model-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
seed-paths: ["seed"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

profile: default

#require-dbt-version: ">=0.13.1"

vars:
  max_ship_date: '1998-12-01'

quoting:
    database: false
    identifier: false
    schema: false

models:
  sales_dwh:
      stg_base:
        schema: STG_BASE
      cln_base:
        schema: CLN_BASE
      ods:
        schema: ODS
      wh:
        schema: DWH
