name: 'sales_dwh'
version: '1.6.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
seed-paths: ["seed"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

profile: default

#require-dbt-version: ">=0.13.1"

vars:
  max_ship_date: '1998-12-01'

quoting:
    database: false
    identifier: false
    schema: false

models:
  sales_dwh:
      #database: sales_dwh_gen_db_dev
      +transient: false
      stg_base:
        #materialized: table
        schema: STG_BASE
      ods:
        schema: ODS
      wh:
        schema: DWH


#on-run-start: "select 'project run started';"
#on-run-end: "select 'i am at end';"